version: '3.0'

services:

  php:
    restart: "no"
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/kanban-board
      
  web:
   restart: "no"
   depends_on:
     - php
   image: nginx:latest
   volumes:
     - ./centra-recruitment.conf:/etc/nginx/conf.d/default.conf
     - ./src:/home/kanban-board
   ports:
     - "80:80"
